### ISSUE TITLE
안뇽하세용 아직은 합성까지는 무리인단계인가여?

### ISSUE THREAD

**Issue by kikikikikinanana** [Kor-SVS/nnsvs-korean-support#1]
검색하다가 우연히 한국어프로젝트있길래와봤습니다!! 혹시 개발중단된건아여 아니면 개발중이신거에요?

**Comment by Cardroid** [comment]
해당 프로젝트에 관심을 가져주셔서 감사합니다.

개인 사정으로 약 2주일 정도 중단되었다가 현재 개발 진행 중입니다.

구체적으로는 현재 보이스 DB 제작 및 모델 동작 검증 중입니다.
한국어를 이식한 학습 및 추론(합성) 코드도 정상적으로 동작하는 것을 확인했습니다.

조만간 hed 및 table 파일이 모델에서 올바르게 동작하는지 검증되면 오픈소스로 업로드할 예정입니다.

자세한 프로젝트 진행 상황은 [이곳](https://github.com/orgs/Kor-SVS/projects/1/views/1)에서 확인 가능합니다.

**Comment by kikikikikinanana** [comment]
알겠습니다 감사합니다!!

**Comment by kikikikikinanana** [comment]
안뇽하세여.. 매일 프로젝트 염탐하고있는데 혹시 잠정중단인가용..?

**Comment by Cardroid** [comment]
아닙니다. 이 프로젝트는 현재 진행 중입니다.

앞서 말씀드렸듯이 비공개 데이터 셋 구축 중입니다.

현재 구상 중인 계획 다음과 같습니다.
1. 데이터 셋 완성 (가장 오래 걸리는 단계)
2. 모델 생성 및 성능 테스트
3. 해당 repo에 반영
4. 문서 작성
5. etc...


다만, 현재 제 건강 상 문제와 개발 일정이 밀리는 관계로 늦어질 수 있습니다.
그 점 양해 부탁드립니다.

**Comment by kikikikikinanana** [comment]
감사합니다
