### ISSUE TITLE
보코더 지원

### ISSUE THREAD

**Issue by Hemiptelea** [Kor-SVS/nnsvs-korean-support#2]
혹시 hifigan과 같은 보코더도 지원하나요?

**Comment by Cardroid** [comment]
Vocoder 모델은 언어 독립적이고, NSF-Vocoder모델은 동작하는 것을 확인했습니다.
아래의 이슈 및 PR들을 확인해 보시는 것을 권장합니다.

학습
- https://github.com/nnsvs/nnsvs/issues/72
- https://github.com/nnsvs/nnsvs/issues/149

추론(사용)
- https://github.com/oatsu-gh/ENUNU/pull/20
- https://github.com/stakira/OpenUtau/pull/540

**Comment by Hemiptelea** [comment]
음성 alignment에 관해 여쭤보고싶습니다.

첨부하신 음소표에 따라 원음 설정하듯이 alignment만 하면 되는것인지요?

**Comment by Cardroid** [comment]
이 링크를 참고하셔서 음소 정렬을 하시면 됩니다.
- https://github.com/Kor-SVS/nnsvs-korean-support/blob/main/doc/How%20to%20phoneme%20alignment.ko.md
- https://github.com/Kor-SVS/nnsvs-korean-support/blob/main/PHONEMES.md

**Comment by JellyBrick** [comment]
`hn-uSFGAN`과 `SiFi-GAN (Source-Filter HiFiGAN)` 지원 예정이라고 하네요.

- https://github.com/nnsvs/nnsvs/pull/157

해당 PR 참고하시면 좋을 것 같습니다.

**Comment by Cardroid** [comment]
해당 이슈는 해결이 되었다고 판단하여 닫겠습니다.
